function mkconfig_sam2bam(varargin)

toolName = mfilename ; 
pnames = {'-samtools_path','-bwa_sam','-out'};
dflts = {'/illumina/applications/samtools-0.1.12a','',pwd}; 

arg = getargs2(pnames,dflts,varargin{:});
print_tool_params2(toolName,1,arg); 

fid = fopen(fullfile(arg.out,[pullname(arg.bwa_sam),'.sam2bam']),'w'); 


header = {'#!/bin/bash',...
    '#$ -cwd',...
    '#$ -S /bin/bash',...
    '#$ -j y',...
    '#$ -pe threaded 2',...
    'set -x'};

for i = 1 : length(header)
    fprintf(fid,'%s\n',header{i}); 
end

fprintf(fid,'%s\n',['time ',fullfile(arg.samtools_path,'samtools'),...
    ' view -bS -o ',fullfile(arg.out,[pullname(arg.bwa_sam),'.bam ']),...
    ' ',arg.bwa_sam]); 
fprintf(fid,'%s\n',['time ',fullfile(arg.samtools_path,'samtools'),...
    ' sort ',fullfile(arg.out,[pullname(arg.bwa_sam),'.bam ']),...
    ' ',fullfile(arg.out,[pullname(arg.bwa_sam),'.sorted'])]);
fprintf(fid,'%s\n',['time ',fullfile(arg.samtools_path,'samtools'),...
    ' index ',fullfile(arg.out,[pullname(arg.bwa_sam),'.sorted.bam'])]);
fclose(fid); 